# Profile information
name: Matthew Ma
title: Matthew Ma
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/fresh" # the subpath of your site, e.g. /blog
url: "https://matthewma1018.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: "profile.php?id=100005709137217"
twitter: "MatthewMa1018"
google-plus: "105499986736051877846"
github: "matthewma1018"

# Contact form
email: #your-email@domain.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
